using System.Text;
using Aurora.Core.Contract;

namespace Aurora.Core.Parsing;

public static class ManifestWriter
{
    public static string SerializeToPkgInfo(AuroraManifest m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Aurora Build Engine");
        
        // Core Identity
        WriteKey(sb, "pkgname", m.Package.Name);
        WriteKey(sb, "pkgver", m.Package.Version);
        WriteKey(sb, "pkgdesc", m.Package.Description);
        WriteKey(sb, "url", m.Metadata.Url);
        WriteKey(sb, "builddate", DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString());
        WriteKey(sb, "packager", m.Package.Maintainer ?? "Aurora");
        WriteKey(sb, "size", m.Files.PackageSize.ToString());
        WriteKey(sb, "arch", m.Package.Architecture);

        // Arrays (Repeated Keys)
        WriteList(sb, "license", m.Metadata.License);
        WriteList(sb, "replaces", m.Metadata.Replaces);
        WriteList(sb, "group", m.Metadata.Groups);
        WriteList(sb, "conflict", m.Metadata.Conflicts);
        WriteList(sb, "provides", m.Metadata.Provides);
        WriteList(sb, "backup", m.Metadata.Backup);

        // Dependencies
        WriteList(sb, "depend", m.Dependencies.Runtime);
        WriteList(sb, "optdepend", m.Dependencies.Optional);
        WriteList(sb, "makedepend", m.Dependencies.Build);
        // checkdepends are not written to binary packages

        return sb.ToString();
    }

    private static void WriteKey(StringBuilder sb, string key, string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return;
        sb.AppendLine($"{key} = {value}");
    }

    private static void WriteList(StringBuilder sb, string key, List<string> items)
    {
        if (items == null) return;
        foreach (var item in items)
        {
            if (string.IsNullOrWhiteSpace(item)) continue;
            sb.AppendLine($"{key} = {item}");
        }
    }
}