using System.Text;
using Aurora.Core.Contract;

namespace Aurora.Core.Parsing;

public static class ManifestWriter
{
    public static string Serialize(AuroraManifest m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Aurora Build Engine");
        
        sb.AppendLine("package:");
        sb.AppendLine($"  name: {m.Package.Name}");
        sb.AppendLine($"  version: {m.Package.Version}");
        sb.AppendLine($"  description: {m.Package.Description}");
        sb.AppendLine($"  architecture: {m.Package.Architecture}");
        sb.AppendLine($"  maintainer: {m.Package.Maintainer}");
        sb.AppendLine($"  build_date: {DateTimeOffset.UtcNow.ToUnixTimeSeconds()}");

        sb.AppendLine("metadata:");
        sb.AppendLine($"  url: {m.Metadata.Url}");
        if (m.Metadata.License.Any()) {
            sb.AppendLine("  license:");
            foreach (var l in m.Metadata.License) sb.AppendLine($"    - {l}");
        }

        sb.AppendLine("dependencies:");
        sb.AppendLine("  runtime:");
        foreach (var d in m.Dependencies.Runtime) sb.AppendLine($"    - {d}");

        sb.AppendLine("files:");
        sb.AppendLine($"  package_size: {m.Files.PackageSize}");
        sb.AppendLine($"  source_hash: {m.Files.SourceHash}");

        return sb.ToString();
    }
}